# Generated by Django 2.2.16 on 2022-07-31 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_activated',
        ),
    ]
