# Generated by Django 2.2.16 on 2022-07-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_user_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
