# Generated by Django 2.2.16 on 2022-07-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_user_verification_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_code',
            new_name='confirmation_code',
        ),
    ]
